"use client";

import { strToU8, zipSync } from "fflate";
import type { ResearchResult } from "./research-types";

const xml = (value: string) => value.replace(/[<>&'\"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[char] || char);
const stamp = () => new Date().toISOString();
const safeName = (value: string) => value.replace(/[\\/:*?"<>|]/g, "-").slice(0, 70);
const download = (bytes: Uint8Array, name: string, type: string) => {
  const blob = new Blob([bytes as BlobPart], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1200);
};

const pText = (text: string, size = 22, color = "10233F", bold = false, align = "l") =>
  `<a:p><a:pPr algn="${align}"/><a:r><a:rPr lang="zh-CN" sz="${size * 100}" b="${bold ? 1 : 0}" dirty="0"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/></a:rPr><a:t>${xml(text)}</a:t></a:r><a:endParaRPr lang="zh-CN" sz="${size * 100}"/></a:p>`;
const shape = (x: number, y: number, w: number, h: number, fill: string, paragraphs: string, line = fill) =>
  `<p:sp><p:nvSpPr><p:cNvPr id="${Math.round(x * 97 + y * 31 + w * 13)}" name="shape"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${Math.round(x * 914400)}" y="${Math.round(y * 914400)}"/><a:ext cx="${Math.round(w * 914400)}" cy="${Math.round(h * 914400)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="${fill}"/></a:solidFill><a:ln w="6350"><a:solidFill><a:srgbClr val="${line}"/></a:solidFill></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square" lIns="127000" rIns="127000" tIns="91440" bIns="91440" anchor="ctr"/><a:lstStyle/>${paragraphs}</p:txBody></p:sp>`;
const slideXml = (content: string) => `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>${content}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`;

function buildSlides(result: ResearchResult) {
  const slides: string[] = [];
  const footer = (n: number) => shape(.45, 7.08, 12.45, .18, "FFFFFF", pText(`产业投资研究 Agent  ·  ${result.meta.cutoff}  ·  ${n}`, 8, "607187"), "FFFFFF");
  slides.push(slideXml(
    shape(0, 0, 13.333, 7.5, "10233F", "", "10233F") +
    shape(.75, .72, 1.55, .36, "F28A32", pText("INVESTMENT RESEARCH", 9, "10233F", true, "ctr"), "F28A32") +
    shape(.75, 2.05, 11.4, 1.35, "10233F", pText(`${result.meta.industry}产业投资研究`, 38, "FFFFFF", true) + pText("四图五清单 · 可追溯决策版", 18, "A9BDD2"), "10233F") +
    shape(.75, 5.75, 11.4, .72, "10233F", pText(`${result.meta.region}｜${result.meta.entity}`, 14, "FFFFFF") + pText(`数据截止：${result.meta.cutoff}`, 10, "A9BDD2"), "10233F")
  ));
  const agenda = ["管理层结论", "四张产业决策图", "五张管理清单", "评分与优先级", "证据链与数据缺口"];
  slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText("研究结构", 28, "10233F", true), "FFFFFF") + agenda.map((t, i) => shape(.7 + (i % 3) * 4.13, 1.55 + Math.floor(i / 3) * 2.15, 3.78, 1.68, i === 0 ? "FFF0E4" : "E8F0F6", pText(`0${i + 1}`, 10, "F28A32", true) + pText(t, 18, "10233F", true), "D7E0E9")).join("") + footer(2)));
  slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText("管理层摘要", 28, "10233F", true), "FFFFFF") + shape(.7, 1.35, 11.9, 1.05, "FFF7EF", pText(result.executiveSummary, 15, "10233F"), "F2C49B") + result.verdicts.slice(0, 3).map((v, i) => shape(.7 + i * 4.05, 2.85, 3.72, 2.55, i === 0 ? "10233F" : "E8F0F6", pText(v.level, 9, i === 0 ? "F28A32" : "1D5C91", true) + pText(v.title, 17, i === 0 ? "FFFFFF" : "10233F", true) + pText(v.rationale, 11, i === 0 ? "D7E0E9" : "607187"), i === 0 ? "10233F" : "D7E0E9")).join("") + footer(3)));
  result.maps.slice(0, 4).forEach((map, mi) => {
    const nodes = map.nodes.slice(0, 6);
    slides.push(slideXml(shape(.55, .35, 12.2, .78, "FFFFFF", pText(`图 ${mi + 1}｜${map.title}`, 27, "10233F", true) + pText(map.question, 10, "607187"), "FFFFFF") + nodes.map((node, i) => {
      const cols = Math.min(3, nodes.length);
      const w = cols === 2 ? 5.65 : 3.72;
      return shape(.7 + (i % cols) * (w + .32), 1.6 + Math.floor(i / cols) * 1.82, w, 1.48, i % 2 ? "FFF0E4" : "E8F0F6", pText(node.label, 15, "10233F", true) + pText(node.detail, 10, "607187"), "D7E0E9");
    }).join("") + shape(.7, 5.65, 11.9, .85, "10233F", pText("主体含义", 9, "F28A32", true) + pText(map.implication, 12, "FFFFFF"), "10233F") + footer(mi + 4)));
  });
  result.lists.slice(0, 5).forEach((list, li) => {
    const items = list.items.slice(0, 6);
    slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText(`清单 ${li + 1}｜${list.name}`, 27, "10233F", true), "FFFFFF") + shape(.65, 1.25, 12.0, .42, "10233F", pText("对象｜状态｜区域｜下一步动作", 10, "FFFFFF", true), "10233F") + items.map((item, i) => shape(.65, 1.75 + i * .79, 12, .64, i % 2 ? "F5F8FA" : "FFFFFF", pText(`${item.name}｜${item.status}｜${item.region}｜${item.nextAction}`, 10, "10233F"), "D7E0E9")).join("") + footer(li + 8)));
  });
  slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText("评分与尽调优先级", 27, "10233F", true), "FFFFFF") + result.scores.slice(0, 7).map((s, i) => shape(.7, 1.3 + i * .7, 11.85, .55, i === 0 ? "FFF0E4" : "F5F8FA", pText(`${i + 1}. ${s.name}  ·  ${s.score}/100  ·  ${s.status}  ·  ${s.rationale}`, 10, "10233F", i === 0), "D7E0E9")).join("") + shape(.7, 6.35, 11.85, .45, "FFFFFF", pText("评分用于确定尽调顺序，不构成投资建议。", 9, "A94D0C", true), "FFFFFF") + footer(13)));
  const gaps = result.dataGaps.slice(0, 6);
  slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText("数据缺口与下一步尽调", 27, "10233F", true), "FFFFFF") + gaps.map((g, i) => shape(.7 + (i % 2) * 6.05, 1.35 + Math.floor(i / 2) * 1.65, 5.7, 1.35, i % 2 ? "FFF0E4" : "E8F0F6", pText(g.item, 14, "10233F", true) + pText(`影响：${g.impact}`, 9, "607187") + pText(`动作：${g.nextAction}`, 9, "1D5C91", true), "D7E0E9")).join("") + footer(14)));
  slides.push(slideXml(shape(.55, .35, 12.2, .7, "FFFFFF", pText("证据来源索引", 27, "10233F", true), "FFFFFF") + result.sources.slice(0, 9).map((s, i) => shape(.7, 1.25 + i * .58, 11.9, .46, i % 2 ? "F5F8FA" : "FFFFFF", pText(`${s.id}｜${s.publisher}｜${s.title}｜${s.date}｜${s.grade}级`, 9, "10233F"), "D7E0E9")).join("") + footer(15)));
  return slides;
}

export function downloadPptx(result: ResearchResult) {
  const slides = buildSlides(result);
  const files: Record<string, Uint8Array> = {};
  const add = (path: string, value: string) => { files[path] = strToU8(value); };
  add("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>${slides.map((_, i) => `<Override PartName="/ppt/slides/slide${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join("")}<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`);
  add("_rels/.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`);
  add("docProps/core.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${xml(result.meta.industry)}产业投资研究</dc:title><dc:creator>产业投资研究 Agent</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${stamp()}</dcterms:created></cp:coreProperties>`);
  add("docProps/app.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>产业投资研究 Agent</Application><Slides>${slides.length}</Slides></Properties>`);
  add("ppt/presentation.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${slides.map((_, i) => `<p:sldId id="${256 + i}" r:id="rId${i + 2}"/>`).join("")}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`);
  add("ppt/_rels/presentation.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>${slides.map((_, i) => `<Relationship Id="rId${i + 2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i + 1}.xml"/>`).join("")}</Relationships>`);
  add("ppt/slideMasters/slideMaster1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1="1D5C91" accent2="F28A32" accent3="2B806C" accent4="607187" accent5="D7E0E9" accent6="10233F" bg1="FFFFFF" bg2="F2F5F8" folHlink="800080" hlink="0000FF" tx1="10233F" tx2="607187"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`);
  add("ppt/slideMasters/_rels/slideMaster1.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`);
  add("ppt/slideLayouts/slideLayout1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`);
  add("ppt/slideLayouts/_rels/slideLayout1.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`);
  add("ppt/theme/theme1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Research"><a:themeElements><a:clrScheme name="Research"><a:dk1><a:srgbClr val="10233F"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="18385F"/></a:dk2><a:lt2><a:srgbClr val="F2F5F8"/></a:lt2><a:accent1><a:srgbClr val="1D5C91"/></a:accent1><a:accent2><a:srgbClr val="F28A32"/></a:accent2><a:accent3><a:srgbClr val="2B806C"/></a:accent3><a:accent4><a:srgbClr val="607187"/></a:accent4><a:accent5><a:srgbClr val="D7E0E9"/></a:accent5><a:accent6><a:srgbClr val="10233F"/></a:accent6><a:hlink><a:srgbClr val="0000FF"/></a:hlink><a:folHlink><a:srgbClr val="800080"/></a:folHlink></a:clrScheme><a:fontScheme name="Research"><a:majorFont><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Microsoft YaHei"/><a:ea typeface="Microsoft YaHei"/><a:cs typeface="Arial"/></a:minorFont></a:fontScheme><a:fmtScheme name="Research"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="6350"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`);
  slides.forEach((s, i) => {
    add(`ppt/slides/slide${i + 1}.xml`, s);
    add(`ppt/slides/_rels/slide${i + 1}.xml.rels`, `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`);
  });
  download(zipSync(files, { level: 6 }), `${safeName(result.meta.industry)}产业投资研究_四图五清单.pptx`, "application/vnd.openxmlformats-officedocument.presentationml.presentation");
}

const cell = (value: string | number, ref: string) => typeof value === "number" ? `<c r="${ref}"><v>${value}</v></c>` : `<c r="${ref}" t="inlineStr"><is><t>${xml(String(value))}</t></is></c>`;
const col = (n: number) => { let s = ""; while (n > 0) { n--; s = String.fromCharCode(65 + n % 26) + s; n = Math.floor(n / 26); } return s; };
function sheet(rows: Array<Array<string | number>>) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"/></sheetViews><cols><col min="1" max="20" width="22" customWidth="1"/></cols><sheetData>${rows.map((row, ri) => `<row r="${ri + 1}">${row.map((v, ci) => cell(v, `${col(ci + 1)}${ri + 1}`)).join("")}</row>`).join("")}</sheetData><autoFilter ref="A1:${col(Math.max(...rows.map(r => r.length)))}${rows.length}"/></worksheet>`;
}
export function downloadXlsx(result: ResearchResult) {
  const sheets = [
    ["项目总览", [["字段", "内容"], ["产业", result.meta.industry], ["区域", result.meta.region], ["实施主体", result.meta.entity], ["数据截止", result.meta.cutoff], ["管理层摘要", result.executiveSummary], ...result.verdicts.map(v => [v.level, v.title, v.rationale, v.evidenceIds.join(",")])]],
    ["四图", [["图名", "核心问题", "节点", "说明", "来源ID", "主体含义"], ...result.maps.flatMap(m => m.nodes.map(n => [m.title, m.question, n.label, n.detail, n.evidenceIds.join(","), m.implication]))]],
    ["五清单", [["清单", "对象", "类型", "状态", "区域", "摘要", "来源ID", "下一步"], ...result.lists.flatMap(l => l.items.map(i => [l.name, i.name, i.type, i.status, i.region, i.summary, i.evidenceIds.join(","), i.nextAction]))]],
    ["评分", [["对象", "类型", "分数", "状态", "理由", "来源ID"], ...result.scores.map(s => [s.name, s.type, s.score, s.status, s.rationale, s.evidenceIds.join(",")])]],
    ["来源索引", [["ID", "发布主体", "标题", "日期", "URL", "等级", "来源类型", "用途"], ...result.sources.map(s => [s.id, s.publisher, s.title, s.date, s.url, s.grade, s.sourceType, s.used])]],
    ["数据缺口", [["缺口", "影响", "下一步"], ...result.dataGaps.map(g => [g.item, g.impact, g.nextAction])]],
  ] as Array<[string, Array<Array<string | number>>]>;
  const files: Record<string, Uint8Array> = {};
  const add = (path: string, value: string) => { files[path] = strToU8(value); };
  add("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`);
  add("_rels/.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`);
  add("xl/workbook.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([name], i) => `<sheet name="${xml(name)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join("")}</sheets></workbook>`);
  add("xl/_rels/workbook.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
  add("xl/styles.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Microsoft YaHei"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="1"><xf xfId="0"/></cellXfs></styleSheet>`);
  sheets.forEach(([, rows], i) => add(`xl/worksheets/sheet${i + 1}.xml`, sheet(rows)));
  download(zipSync(files, { level: 6 }), `${safeName(result.meta.industry)}产业研究数据库.xlsx`, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}
