import type { ResearchResult } from "./research-types";

const evidence = (sourceIds: string[]) => sourceIds;

export const eldercareRobotSample: ResearchResult = {
  meta: {
    taskId: "sample-eldercare-robot-hubei",
    industry: "养老机器人",
    region: "湖北省",
    entity: "地方国资产业投资平台（示范）",
    mode: "full",
    cutoff: "2026-07-31",
    generatedAt: "2026-07-31T08:00:00+08:00",
  },
  executiveSummary: "以康复训练、辅助出行和机构配送为近期场景入口，以武汉研发验证与都市圈制造协同为落点；失能护理和通用人形产品须经安全、支付与真实利用率里程碑后再扩大投入。",
  verdicts: [
    { level: "优先尽调", title: "康复机器人与辅助出行", rationale: "产品成熟度、机构采购路径和临床康复需求相对清晰，适合通过示范中心、租赁运营和成长轮股权形成组合验证。", evidenceIds: evidence(["S02", "S08", "S22", "S23", "S25"]) },
    { level: "场景先行", title: "机构配送、清洁与巡检", rationale: "可在养老机构用工时节省、任务成功率和故障闭环验证价值，先试点后集采。", evidenceIds: evidence(["S31", "S38", "S39"]) },
    { level: "里程碑培育", title: "失能护理与具身智能", rationale: "需求刚性但直接接触老人，安全责任、产品资质和支付闭环尚需小样本强监督验证。", evidenceIds: evidence(["S02", "S17", "S41"]) },
    { level: "暂停边界", title: "展示型通用产品直接规模采购", rationale: "若无法给出真实任务成功率、人工接管率、单床成本和复购证据，不进入规模化采购或重资产建设。", evidenceIds: evidence(["S02", "S17"]) },
  ],
  maps: [
    { title: "产业链全景图", question: "湖北应在产业链什么位置建立能力？", nodes: [
      { label: "核心部件", detail: "精密传动、关节模组、传感与控制", evidenceIds: ["S21"] },
      { label: "康复整机", detail: "上肢、下肢、外骨骼与评估训练", evidenceIds: ["S22", "S23", "S25", "S32"] },
      { label: "服务整机", detail: "配送、清洁、巡检与辅助出行", evidenceIds: ["S24", "S38", "S39"] },
      { label: "护理产品", detail: "移位、排泄、翻身及安全监护", evidenceIds: ["S02", "S41"] },
      { label: "接入运营", detail: "设备接入、工单、支付和数据闭环", evidenceIds: ["S05", "S07"] },
    ], implication: "武汉布局研发、验证、区域总部和运营平台，黄冈等地承接部件与制造；场景入口与设备投资分开决策。" },
    { title: "应用领域与产品价值图", question: "谁使用、谁购买、谁付费，如何验收？", nodes: [
      { label: "医院康复", detail: "医院采购；以临床效果、设备利用率验收", evidenceIds: ["S22", "S25"] },
      { label: "养老机构", detail: "机构采购/租赁；以工时、险情和单床成本验收", evidenceIds: ["S02", "S39"] },
      { label: "居家养老", detail: "个人、家庭或服务包支付；关注可负担与售后", evidenceIds: ["S01", "S24"] },
      { label: "失能护理", detail: "机构与家庭共同决策；强监督验证安全边界", evidenceIds: ["S02", "S41"] },
      { label: "康养文旅", detail: "运营方采购；验证频次、体验与转化", evidenceIds: ["S15", "S42"] },
    ], implication: "优先选择任务高频、付款主体明确、12个月内可形成对照数据的场景。" },
    { title: "技术路线与投资优先级图", question: "哪些技术近期导入，哪些需要继续等待？", nodes: [
      { label: "近期导入", detail: "康复训练、配送巡检、辅助出行", evidenceIds: ["S22", "S24", "S39"] },
      { label: "中期培育", detail: "助行外骨骼、机构协作与多机调度", evidenceIds: ["S23", "S31"] },
      { label: "项目验证", detail: "移位、排泄等失能护理", evidenceIds: ["S02", "S41"] },
      { label: "长期储备", detail: "通用人形与非结构环境自主作业", evidenceIds: ["S17"] },
      { label: "关键指标", detail: "任务成功率、接管率、险情率、利用率", evidenceIds: ["S02"] },
    ], implication: "技术先进性不直接等于投资优先级；以场景数据、合规资质和单位经济性解锁下一阶段。" },
    { title: "区域分布与产业布局图", question: "湖北省内如何分工，并从外部导入什么？", nodes: [
      { label: "武汉—光谷", detail: "研发、3D视觉、康复产品、创新平台", evidenceIds: ["S16", "S17", "S31", "S32"] },
      { label: "武汉经开/汉江湾", detail: "中试组装、供应链与城市服务场景", evidenceIds: ["S16"] },
      { label: "黄冈", detail: "精密传动与机器人关节配套", evidenceIds: ["S21"] },
      { label: "黄石", detail: "整机及零部件制造承载", evidenceIds: ["S20"] },
      { label: "孝感/咸宁", detail: "医疗康复、康养与文旅试点", evidenceIds: ["S15", "S42"] },
    ], implication: "区域公共资源不等同于实施主体拥有；每个落点需进一步核验载体、权限、预算和合作协议。" },
  ],
  lists: [
    { name: "产业集群清单", items: [
      { name: "武汉—光谷", type: "核心布局区", status: "研发验证与总部", region: "武汉", summary: "机器人谷、湖北人形机器人创新中心、AI与高校科研资源集聚。", evidenceIds: ["S16", "S17"], nextAction: "建设康养机器人测试与数据专区" },
      { name: "武汉经开区—汉江湾", type: "核心布局区", status: "中试制造与场景", region: "武汉", summary: "承接中试组装、汽车供应链能力复用与城市运营机器人适配。", evidenceIds: ["S16"], nextAction: "核验厂房、产线与招商政策" },
      { name: "黄冈", type: "协同承载区", status: "核心部件", region: "黄冈", summary: "精密传动与机器人关节可形成省内补链。", evidenceIds: ["S21"], nextAction: "开展关节模组负载谱联合验证" },
      { name: "黄石", type: "协同承载区", status: "规模制造", region: "黄石", summary: "具备机器人整机与零部件招商和工业场景基础。", evidenceIds: ["S20"], nextAction: "核验具体载体与在建项目" },
      { name: "孝感—咸宁", type: "场景协同区", status: "康复与康养", region: "武汉都市圈", summary: "适合医疗康复、康养文旅和短期康复试点。", evidenceIds: ["S15", "S42"], nextAction: "筛选机构并建立统一验收口径" },
    ] },
    { name: "政策清单", items: [
      { name: "发展银发经济增进老年人福祉的意见", type: "国家政策", status: "有效", region: "全国", summary: "支持智能护理、家庭服务和健康监测等产品发展。", evidenceIds: ["S01"], nextAction: "匹配银发科技项目与金融工具" },
      { name: "智能养老服务机器人结对攻关与场景应用试点", type: "国家试点", status: "2025—2027", region: "全国", summary: "围绕居家、社区和机构开展产品与场景攻关。", evidenceIds: ["S02"], nextAction: "组织企业、机构和高校联合申报" },
      { name: "湖北人形机器人创新中心建设", type: "省级平台", status: "建设中", region: "湖北省", summary: "建设研发验证、产业孵化和招商开放平台。", evidenceIds: ["S17"], nextAction: "共建养老机器人测试专区" },
      { name: "武汉市人工智能+行动方案", type: "市级政策", status: "有效", region: "武汉", summary: "布局智慧养老和人形机器人应用场景。", evidenceIds: ["S14"], nextAction: "形成城市级养老机器人场景包" },
    ] },
    { name: "重点企业清单", items: [
      { name: "傅利叶智能", type: "康复机器人", status: "优先尽调", region: "上海/拟导入武汉", summary: "康复产品和机构客户基础较强，适合示范中心与股权跟踪。", evidenceIds: ["S22"], nextAction: "核验注册证、收入结构、估值与退出" },
      { name: "程天科技", type: "外骨骼与助行", status: "优先尽调", region: "杭州/拟导入武汉", summary: "医疗康复与消费级产品线，可开展华中临床及养老验证。", evidenceIds: ["S23"], nextAction: "核验销售规模、成本、注册证与售后" },
      { name: "邦邦机器人", type: "辅助出行", status: "招引与投资", region: "上海/拟导入湖北", summary: "智能辅助出行产品具备商业化基础。", evidenceIds: ["S24"], nextAction: "核验收入、毛利、融资条款与海外合规" },
      { name: "翔宇医疗", type: "康复医疗设备", status: "产业合作", region: "河南/湖北协同", summary: "上市公司康复渠道和解决方案能力可用于区域合作。", evidenceIds: ["S25"], nextAction: "拆分机器人业务收入及产品资质" },
      { name: "武汉海沁医疗", type: "本地康复机器人", status: "场景验证", region: "武汉", summary: "本地企业，公开披露康复机器人及医疗器械进展。", evidenceIds: ["S32"], nextAction: "逐项核验注册范围、订单与量产能力" },
      { name: "光谷东智", type: "本地康养机器人", status: "里程碑培育", region: "武汉", summary: "适合以本地机构试点验证产品标准化和交付能力。", evidenceIds: ["S31", "S43"], nextAction: "核验多机构利用率、收入和安全数据" },
    ] },
    { name: "重点项目清单", items: [
      { name: "养老机器人场景接入与运营平台", type: "平台项目", status: "建议", region: "武汉", summary: "统一设备接入、需求池、试点工单、运维和服务支付。", evidenceIds: ["S05", "S07"], nextAction: "先确认主体权限、数据合规和运营预算" },
      { name: "武汉康复机器人示范中心", type: "示范项目", status: "建议", region: "武汉", summary: "形成评估—训练—随访闭环，分阶段验证利用率与支付。", evidenceIds: ["S08", "S22", "S23", "S25"], nextAction: "编制可研并锁定医院与康养机构" },
      { name: "养老机构配送清洁巡检百床试点", type: "场景项目", status: "建议", region: "武汉", summary: "在不同楼宇条件机构开展12个月对照试验。", evidenceIds: ["S31", "S38", "S39"], nextAction: "建立工时、故障、安全和单床成本基线" },
      { name: "失能护理机器人安全验证", type: "研发与场景", status: "建议", region: "武汉", summary: "围绕移位、排泄等高刚需任务开展小样本强监督验证。", evidenceIds: ["S02", "S41"], nextAction: "明确第三方检测、保险和责任协议" },
      { name: "科峰传动关节联合验证", type: "补链项目", status: "储备", region: "黄冈+武汉", summary: "用养老及服务机器人负载谱验证关节模组与扩产条件。", evidenceIds: ["S21"], nextAction: "核验产能利用率、客户订单与质量体系" },
    ] },
    { name: "产业问题清单", items: [
      { name: "需求—产品错配", type: "市场", status: "高", region: "湖北省", summary: "展示型产品若未对应具体护理任务，容易出现试点热闹但复购低。", evidenceIds: ["S02"], nextAction: "按老人分级、任务SOP和验收指标立项" },
      { name: "支付闭环不清", type: "商业模式", status: "高", region: "湖北省", summary: "居家支付能力有限，机构资本预算与运营预算分离。", evidenceIds: ["S01", "S08"], nextAction: "组合租赁、按次、服务包和试点资金" },
      { name: "安全与责任边界", type: "合规", status: "高", region: "湖北省", summary: "移位、排泄和翻身等接触任务失效后果严重。", evidenceIds: ["S02"], nextAction: "强监督试点、失效保护、检测和保险并行" },
      { name: "医疗器械资质与临床证据", type: "医疗合规", status: "高", region: "湖北省", summary: "注册范围、适应症与宣传口径必须逐产品核验。", evidenceIds: ["S32", "S36"], nextAction: "核验NMPA注册证与真实世界终点" },
      { name: "系统孤岛", type: "平台", status: "中高", region: "武汉", summary: "机器人、养老平台、楼宇和健康数据接口不统一。", evidenceIds: ["S05", "S07"], nextAction: "制定统一设备身份、API和工单规范" },
    ] },
  ],
  scores: [
    { name: "康复机器人", type: "产品方向", score: 84, status: "优先尽调与示范", rationale: "机构需求、产品成熟度和验证路径相对明确", evidenceIds: ["S22", "S23", "S25"] },
    { name: "辅助出行", type: "产品方向", score: 79, status: "招引与场景验证", rationale: "商业化基础较好，需验证支付与售后", evidenceIds: ["S24"] },
    { name: "机构配送巡检", type: "产品方向", score: 77, status: "先试点后集采", rationale: "任务清晰，可形成量化运营数据", evidenceIds: ["S38", "S39"] },
    { name: "失能护理机器人", type: "产品方向", score: 63, status: "里程碑培育", rationale: "需求刚性，但安全、合规和支付证据不足", evidenceIds: ["S02", "S41"] },
    { name: "武汉康复机器人示范中心", type: "项目", score: 81, status: "进入可研", rationale: "可同时验证产品、场景、运营和区域招引", evidenceIds: ["S22", "S23", "S25"] },
  ],
  sources: [
    { id: "S01", publisher: "国务院办公厅", title: "关于发展银发经济增进老年人福祉的意见", date: "2024-01-15", url: "https://chinajob.mohrss.gov.cn/h5/c/2024-01-16/394987.shtml", grade: "A", sourceType: "政府", used: "产业方向、支付与场景" },
    { id: "S02", publisher: "工业和信息化部等", title: "智能养老服务机器人结对攻关与场景应用试点通知", date: "2025-06-10", url: "https://www.ncsti.gov.cn/kjdt/tzgg/202506/t20250610_207396.html", grade: "A", sourceType: "政府", used: "场景、产品成熟度与合规" },
    { id: "S05", publisher: "武汉市财政局", title: "武汉市城市建设投资开发集团有限公司公开简介", date: "2026-03-18", url: "https://czj.wuhan.gov.cn/FBJD/XXGKML/CZGK/dftzgs/202509/t20250903_2643258.html", grade: "A", sourceType: "政府", used: "实施主体公开资源边界" },
    { id: "S07", publisher: "武汉市民政局", title: "2024年度养老服务工作公开报告", date: "2025", url: "https://mzj.wuhan.gov.cn/zwgk_918/fdzdgk/czzj/202510/P020251011400514790950.pdf", grade: "A", sourceType: "政府", used: "武汉养老场景" },
    { id: "S08", publisher: "武汉市人民政府", title: "武汉市养老服务设施建设三年行动方案（2025—2027年）", date: "2025-03-21", url: "https://www.wuhan.gov.cn/zwgk/xxgk/zfwj/bgtwj/202503/t20250321_2555479.shtml", grade: "A", sourceType: "政府", used: "设施与示范场景" },
    { id: "S14", publisher: "武汉市人民政府", title: "武汉市‘人工智能+’行动方案", date: "2026-03", url: "https://www.wuhan.gov.cn/zwgk/xxgk/zfwj/bgtwj/202603/t20260323_2743481.shtml", grade: "A", sourceType: "政府", used: "武汉AI与养老场景" },
    { id: "S15", publisher: "湖北省人民政府", title: "湖北省‘十五五’规划相关公开信息", date: "2026-04-23", url: "https://www.hubei.gov.cn/zwgk/hbyw/hbywqb/202604/t20260423_5920799.shtml", grade: "A", sourceType: "政府", used: "省域协同与银发经济" },
    { id: "S16", publisher: "武汉市人民政府", title: "武汉机器人产业集聚区与机器人谷建设信息", date: "2025-06-23", url: "https://www.wuhan.gov.cn/sy/whyw/202506/t20250623_2598697.shtml", grade: "A", sourceType: "政府", used: "武汉产业集群" },
    { id: "S17", publisher: "湖北省经济和信息化厅", title: "湖北人形机器人创新中心建设信息", date: "2025-06", url: "https://jxt.hubei.gov.cn/bmdt/rdjj/202506/t20250605_5680578.shtml", grade: "A", sourceType: "政府", used: "创新平台与技术验证" },
    { id: "S20", publisher: "湖北省经济和信息化厅", title: "黄石市机器人产业行动计划公开信息", date: "2025-10-20", url: "https://jxt.hubei.gov.cn/bmdt/szgz/202510/t20251020_5794283.shtml", grade: "A", sourceType: "政府", used: "黄石制造承载" },
    { id: "S21", publisher: "科峰传动", title: "企业及机器人精密传动业务公开资料", date: "2026-07查询", url: "https://www.kofon.com.cn/", grade: "B", sourceType: "企业官网", used: "湖北核心部件与黄冈布局" },
    { id: "S22", publisher: "傅利叶智能", title: "康复机器人产品与商业进展", date: "2026-07查询", url: "https://www.fftai.cn/products-rehabilitation", grade: "B", sourceType: "企业官网", used: "康复产品与机构应用" },
    { id: "S23", publisher: "程天科技", title: "UGO系列外骨骼及企业公开资料", date: "2026-07查询", url: "https://www.roboct.com/", grade: "B", sourceType: "企业官网", used: "外骨骼、助行与企业筛选" },
    { id: "S24", publisher: "邦邦机器人", title: "智能辅助出行产品及融资公开资料", date: "2026-07查询", url: "https://bangbangrobotics.com/about", grade: "B", sourceType: "企业官网", used: "辅助出行与企业筛选" },
    { id: "S25", publisher: "翔宇医疗", title: "2025年度报告及康复产品资料", date: "2026-04", url: "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12170111&stockid=688626", grade: "A", sourceType: "上市公司公告", used: "财务与康复产品" },
    { id: "S31", publisher: "武汉市投资促进局", title: "光谷东智智慧康养解决方案公开信息", date: "2026-06-26", url: "https://tc.wuhan.gov.cn/tzwh/tzzx/202606/t20260626_2813476.shtml", grade: "A", sourceType: "政府", used: "武汉本地康养机器人" },
    { id: "S32", publisher: "武汉海沁医疗", title: "康复机器人及企业公开资料", date: "2026-07查询", url: "https://www.epmomedical.com/", grade: "B", sourceType: "企业官网", used: "武汉本地康复企业" },
    { id: "S36", publisher: "国家卫生健康委", title: "2024年我国卫生健康事业发展统计公报", date: "2025-12", url: "https://www.nhc.gov.cn/guihuaxxs/c100132/202512/9db8db5488a748c4b1e1068a4a8c4455.shtml", grade: "A", sourceType: "政府", used: "医疗供给与合规背景" },
    { id: "S38", publisher: "普渡机器人", title: "清洁与配送机器人产品公开介绍", date: "2026-07查询", url: "https://www.pudurobotics.com/", grade: "B", sourceType: "企业官网", used: "机构清洁配送产品" },
    { id: "S39", publisher: "擎朗智能", title: "服务机器人产品与场景公开介绍", date: "2026-07查询", url: "https://www.keenon.com/", grade: "B", sourceType: "企业官网", used: "养老机构服务机器人" },
    { id: "S41", publisher: "呵康科技", title: "失能老人护理机器人公开介绍", date: "2026-07查询", url: "https://www.chinaevercare.com/index.aspx", grade: "C", sourceType: "企业官网", used: "失能护理产品线索" },
    { id: "S42", publisher: "武汉市科技局", title: "手智创新艾灸机器人价格及落地信息", date: "2026-04-09", url: "https://kjj.wuhan.gov.cn/xwzx_8/kjspxw/202604/t20260409_2750862.html", grade: "A", sourceType: "政府", used: "武汉康养文旅场景" },
    { id: "S43", publisher: "武汉市发展改革委", title: "光谷东智全国总部落地信息", date: "2025-03-31", url: "https://fgw.wuhan.gov.cn/xwzx/mtgz/202503/t20250331_2560423.html", grade: "A", sourceType: "政府", used: "本地企业与招商项目" },
  ],
  dataGaps: [
    { id: "G01", module: "企业", item: "非上市企业收入、毛利、订单和估值", impact: "企业投资排序仍需财务尽调", nextAction: "获取审计报告、合同与融资条款" },
    { id: "G02", module: "产品", item: "康复及护理产品逐项注册证范围", impact: "影响医疗机构采购和应用边界", nextAction: "按产品型号核验NMPA信息" },
    { id: "G03", module: "ROI", item: "养老机构人员工时、设备利用率与维护成本基线", impact: "无法形成可靠单床经济性", nextAction: "通过百床试点建立12个月对照数据" },
    { id: "G04", module: "主体资源", item: "实施主体可实际调度的养老机构、物业和资金权限", impact: "区域资源不能直接视为主体资产", nextAction: "内部确认权属、授权、预算与合作协议" },
  ],
  database: {
    boundaries: { definition: "面向老年人居家、社区、机构、康复和护理任务的机器人整机、关键部件、软件平台及运营服务。", included: ["康复训练", "辅助出行", "机构服务", "失能护理", "安全监护", "接入运营"], excluded: ["仅面向工业生产且无养老应用证据的机器人", "纯展示概念产品"], valueChainBoundary: "核心部件—整机—场景—平台—运营与支付", productTaxonomy: ["康复", "助行", "护理", "服务", "陪伴监护"], businessModels: ["销售", "租赁", "服务包", "联合运营", "平台接入"], statisticalCaliber: "示范数据沿用养老机器人增强基础数据库口径", geography: "全国扫描、湖北省深挖", targetAudience: "地方国资产业投资平台" },
    products: [], marketMetrics: [], technologies: [], industryChain: [],
    regions: [
      { id: "RG001", tier: "核心布局区", region: "武汉", cluster: "武汉—光谷", enterprises: "光谷东智、海沁医疗等", research: "高校院所与创新中心", platforms: "机器人谷、湖北人形机器人创新中心", capital: "省市产业资本", manufacturing: "研发中试", scenarios: "医院、养老、城市服务", strength: "AI、视觉、科研与场景", weakness: "养老专项商业化仍需验证", role: "研发验证与总部", sourceIds: ["S16", "S17", "S32"] },
      { id: "RG003", tier: "协同承载区", region: "黄冈", cluster: "精密传动与关节配套", enterprises: "科峰传动", research: "待补充", platforms: "省级协同资源", capital: "区域产业资本", manufacturing: "核心部件", scenarios: "机器人负载测试", strength: "精密传动", weakness: "整机和场景较弱", role: "部件制造", sourceIds: ["S21"] },
    ],
    policies: [], enterprises: [], projects: [], problems: [], resources: [], scoreWeights: [], scoreItems: [], roiScenarios: [], changeLog: [], searchLog: [],
  },
  slides: [{ title: "封面", subtitle: "湖北省养老机器人产业投资研究", bullets: ["全国扫描·湖北深挖·场景验证·资本匹配"], evidenceIds: [] }],
};
